OPM/opm-polymer

opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.cpp
This PR adapt to API changes in opm-autodiff, see commits https://github.com/dr-robertk/opm-autodiff/commit/e7e63e198938eb30590a78c75b935656595369f8
=> Adapte to FIBO wellstate API changes in opm-autodiff.

examples/sim_poly2p_comp_reorder.cpp, examples/sim_poly2p_incomp_reorder.cpp, opm/polymer/PolymerInflow.cpp, opm/polymer/PolymerInflow.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.cpp
Due to commit https://github.com/joakim-hove/opm-parser/commit/6628941c9c9d781db9ec8e3ac05a3a8dc49dcf21
=> Change PolymerInflow constructor interface.

examples/sim_poly_fibo_ad.cpp
Method thresholdPressure signature is changed - changing parameter list for method call
=> OPM-166: opm-core method thresholdPressures signature has changed

opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.cpp
This adapts to OPM/opm-core#758.
=> Adapt to API change in WellsManager.

opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp
This is necessary to match OPM/opm-autodiff#330.
=> Follow API change in BlackoilPropsAdInterface.

opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp, opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp, opm/polymer/fullyimplicit/PolymerPropsAd.cpp
This is a companion to OPM/opm-autodiff#334, and should be merged if that PR is merged.
=> Adapt to API change for AutoDiffBlock class.

debian/libopm-polymer1-dbg.install, debian/rules
Please backport to release branch.
=> update debian packaging

CMakeLists_files.cmake, opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp, opm/polymer/fullyimplicit/WellStateFullyImplicitBlackoilPolymer.hpp
This PR requires OPM/opm-autodiff#381, and should be discussed there.
Edit: corrected link.
=> Start refactor fully implicit polymer solver

examples/sim_poly2p_comp_reorder.cpp, opm/polymer/SimulatorCompressiblePolymer.cpp, opm/polymer/SimulatorCompressiblePolymer.hpp, opm/polymer/TransportSolverTwophasePolymer.cpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp, opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp, opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp, opm/polymer/fullyimplicit/PolymerPropsAd.cpp, opm/polymer/fullyimplicit/PolymerPropsAd.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
Also fix a few minor issues along the way.
=> Silence multiple warnings.

examples/flow_polymer.cpp, opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp, opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver.hpp, opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
Adding the flag for PLYSHLOG keyword.
=> Adding the flag for PLYSHLOG keyword.

opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
See https://github.com/OPM/opm-polymer/issues/129
=> Fix parameter errors.

opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
To follow the corresponding change in PR OPM/opm-autodiff#406. 
The results have been verified with the working examples.
=> change the parameter order addWellContributionToMassBalanceEq().

CMakeLists_files.cmake, opm/polymer/Point2D.hpp, opm/polymer/PolymerProperties.cpp, opm/polymer/PolymerProperties.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp, opm/polymer/fullyimplicit/PolymerPropsAd.cpp, opm/polymer/fullyimplicit/PolymerPropsAd.hpp
This PR addresses the application of shear-thinning effects based on the PLYSHLOG keyword. The commit history tells pretty accurately about the summary of what are included in this PR. 
The development of this PR (began earlier and ended later) is kind of in parallel with the previous re-factoring process, and may mess up with some of efforts of the re-factoring. There are definitely some space for re-factoring, please suggest whatever is necessary. I think it might be the efficient way to improve the code by creating a PR here.
The PR is verified with our current working examples.
=> Adding shear-thinning calculation with PLYSHLOG

opm/polymer/Point2D.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
This fixes a few warnings from the last PR.
=> Fix warnings

examples/flow_polymer.cpp, opm/polymer/PolymerProperties.cpp, opm/polymer/PolymerProperties.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp, opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp, opm/polymer/fullyimplicit/PolymerPropsAd.cpp, opm/polymer/fullyimplicit/PolymerPropsAd.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp
Adding shear-rate based shear-thinning calculation based on keyword SHRATE. 
The PR has been verified with our working examples.
=> Adding shear-thinning effects based on keyword SHRATE

opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
This is a companion PR of OPM/opm-autodiff#408. Please do not merge before PR OPM/opm-autodiff#408 got merged. 
The results are verified with our working examples (small cases) with small changes in the residual history.
=> adapting to the change in autodiff#408

examples/flow_polymer.cpp, examples/sim_poly2p_comp_reorder.cpp, examples/sim_poly2p_incomp_reorder.cpp, examples/sim_poly_fi2p_comp_ad.cpp
Followup to: https://github.com/OPM/opm-parser/pull/527
=> Added ParseMode argument

opm/polymer/PolymerProperties.hpp
Followup to: https://github.com/OPM/opm-parser/pull/570
=> Using TableManager to get tables.

examples/flow_polymer.cpp, examples/sim_poly_fi2p_comp_ad.cpp
this is analogous to https://github.com/OPM/opm-autodiff/pull/422
(note that the non-AD simulators are not affected by this because they only create a single properties object.)
=> AD simulators: include Evaluation.hpp before the other headers, only initialize the satfuncs once

examples/flow_polymer.cpp, examples/sim_poly_fi2p_comp_ad.cpp
=> Update for removed constructor args.

redhat/opm-polymer.spec
=> update redhat packaging

examples/flow_polymer.cpp
This makes the startup message more similar to the rest of the Flow family, and uses the moduleVersion() utility.
=> Use moduleVersion() in startup message.

opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp, opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
=> Fix compile failures from recent updates in core and autodiff

opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp, opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp
Adapts to OPM/opm-autodiff#536.
=> Adapt to refactored/renamed NonlinearSolver (was NewtonSolver).

examples/flow_polymer.cpp, examples/sim_poly_fi2p_comp_ad.cpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp, opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer_impl.hpp
this fixes the build once OPM/opm-autodiff#542 has been merged.
=> adapt to the "mutable geology" changes from opm-autodiff
