OPM/opm-polymer

examples/flow_polymer.cpp
examples/sim_poly_fi2p_comp_ad.cpp

this PR adapts to the EclipseWriter API change of OPM/opm-core#772 and must thus be merged synchronously.

pass the deck to the output writer

---

examples/flow_polymer.cpp
examples/sim_poly_fi2p_comp_ad.cpp

This reverts commit 71987ae3b038c141a673ae1c1037f63ed695e595.
it is now required for OPM/opm-core#776

Revert "pass the deck to the output writer"

---

examples/flow_polymer.cpp

commit summary
1. Adding a start-up message similar to the nicer start-up message in PR OPM/opm-autodiff#355. The difference is that the message is 3 letter wider. 
2. Accept single deck filename as command line argument, same with PR OPM/opm-autodiff#356. The only difference is adding a linebreaker in the third option of how to specify a deck input. 
As a result, the three methods to specify a deck file now are
a) as a command line argument by itself
b) as a command line parameter with the syntax deck_filename=<path to your deck>, or
c) as a parameter in a parameter file (.param or .xml) passed to the program.
3. And removing a white space.

Adding startup message flow polymer and accpting single deck filename as command line argument.

---

opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver.hpp
opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp

Summary of the changes. 
1.  SolverParameter::reset() - new default parameters
2.  minIter() - add method, data member etc. and use of it in step().
3.  No longer throw on solver failure, just return -1 from step().
4.  Change computeRelPerm() and computePressures() to match autodiff.
5.  Remove unused method computeRelPermWells().
6.  Change transMult() and poroMult() to match autodiff.
The updated code has been tested and verified with our current working DATA file.

Minor update and adaption to match opm-autodiff

---

opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver.hpp
opm/polymer/fullyimplicit/FullyImplicitBlackoilPolymerSolver_impl.hpp

Summary of the updates.
1.  variableState(), removing unused block patterns and using std::move.
2. computeMassFlux(), handling one phase each time. Polymer treatment is included as a part of the water phase, since whater phase will be affected by polymer. 
3. updateWellControls(), no longer update primary variables in the function and the function is moved to assemble()
4. addWellEq(), to match PR OPM/opm-autodiff#371.
The changes have been tested and verified with out current working DATA file.

Adapting some updates in opm-autodiff to opm-polymer. 

---

opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp

Older compilers, e.g., GCC 4.4., do not understand the "simple-type-specifier" syntax of C++11's [`friend`](http://en.cppreference.com/w/cpp/language/friend) declarations. Typical responses are
```
error: a class-key must be used when declaring a friend
error: friend declaration does not name a class or function
```
Restore build on older compilers (e.g., GCC prior to 4.7) by inserting the `class` keyword.

Restore build on older compilers

---

opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp

This is done with dummy types since the class in question (`SimulatorFullyImplicitCompressiblePolymer`) does not use a Model/Solver split.
With this, OPM/opm-autodiff#393 can be merged.

Satisfy interface requirements of SimulatorBase.

---

opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp

This is done by using the base class model_param_ and avoid recreating it.

Avoid parameter spamming in output.

---

opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp

This makes the polymer model able to run with `solve_welleq_initially=true`.
It also makes the code clearer.
This PR must be merged simultaneously with OPM/opm-autodiff#400.

Move polymer code from extraAddWellEq to addWellContributionToMassBalanceEq.

---

opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer_impl.hpp

BlackoilModelBase now requires an EclipseState constructor argument.
Also silenced two minor warnings.

Update to match changes in opm-autodiff.

---

opm/polymer/PolymerProperties.cpp

A bug was discovered by some new examples. In the current master branch, we compared the obtained water velocity (shear rate) with the max velocity input in the `PLYSHLOG` table to see if the obtained water velocity is out of range of the range in the table. With some shear-thinning cases, even the water velocity is in the velocity range specified in the table, the shear-multiplier calculation still can be failed, when the sheared velocity (which is bigger than the pre-sheared water velocity) is out of velocity range input in the table. 
The suggested standard in this PR is more correct by comparing the sheared velocity with the maximum velocity input in the table to determine if the failure is due to the water velocity is too big to calculate the shear-multiplier. 
The PR is tested with …

correcting the determination of out-of-table-range velocity

---

examples/flow_polymer.cpp

Function `Opm::thresholdPressures()` gained a new `ParseMode` parameter in commit OPM/opm-core@09aa2b7 (PR OPM/opm-core#857).  Chase updated call interface.

Restore build of flow_polymer

---

opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.hpp
opm/polymer/fullyimplicit/PolymerPropsAd.cpp

This makes the polymer simulators compile again, after OPM/opm-autodiff#456 was merged.

Update for opm-autodiff changes.

---

examples/flow_polymer.cpp
examples/sim_poly_fi2p_comp_ad.cpp

The constructor of class `BlackoilOutputWriter` gained a new parameter in commit OPM/opm-autodiff@299b0aa (OPM/opm-autodiff#484).  Honour new API requirement.

Follow API update of BlackoilOutputWriter

---

opm/polymer/fullyimplicit/BlackoilPolymerModel.hpp
opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp

With the changes in OPM/opm-autodiff#492, the custom getConvergence() and convergenceReduction() methods are no longer required and can be deleted.
Also, we add the material name "Polymer" so that reporting works properly.
Edit: this has been tested with a simple polymer test case, and gives slightly different results from the master branch. However this is because the master branch did not incorporate a change made in opm-autodiff in June (no longer scaling the well flux residual with dt for convergence tests). With this PR, they will use the same implementation and not get out of sync like that

Refactor getConvergence()

---

examples/flow_polymer.cpp
examples/sim_poly2p_comp_reorder.cpp
examples/sim_poly2p_incomp_reorder.cpp
examples/sim_poly_fi2p_comp_ad.cpp
examples/test_singlecellsolves.cpp
opm/polymer/CompressibleTpfaPolymer.cpp
opm/polymer/GravityColumnSolverPolymer_impl.hpp
opm/polymer/IncompPropertiesDefaultPolymer.hpp
opm/polymer/IncompTpfaPolymer.cpp
opm/polymer/PolymerProperties.cpp
opm/polymer/PolymerProperties.hpp
opm/polymer/SimulatorCompressiblePolymer.cpp
opm/polymer/SimulatorPolymer.cpp
opm/polymer/TransportSolverTwophaseCompressiblePolymer.cpp
opm/polymer/TransportSolverTwophasePolymer.cpp
opm/polymer/fullyimplicit/BlackoilPolymerModel_impl.hpp
opm/polymer/fullyimplicit/FullyImplicitCompressiblePolymerSolver.cpp
opm/polymer/fullyimplicit/SimulatorFullyImplicitBlackoilPolymer.hpp
opm/polymer/fullyimplicit/SimulatorFullyImplicitCompressiblePolymer.hpp

this makes the polymer module compile again after the error macros have been moved to opm-common. It seems like I forgot to open a PR for the polymer module when doing OPM/opm-common#55. sorry for the hiccup.

use the error macros from opm-common

---

opm/polymer/PolymerProperties.hpp

silencing a shadowing warning when processing the SHRATE constant. 
No functional change.

silencing a shadowing warning related to shrate.

---

opm/polymer/PolymerProperties.cpp
opm/polymer/PolymerProperties.hpp

correcting the typo when reading PLYROCK table.
PlymaxTable was used instead.
This should fix OPM/opm-data#76 .

Correcting plyrocktable reading typo

---

examples/flow_polymer.cpp

to be able to determine the threshold pressure from the initial
condition it needs to be able to access the initial condition, i.e.,
the initial simulator state, material properties object and gravity
constant need to be passed to the thresholdPressure() function.
this is a follow-up of OPM/opm-core#907.

adapt to the threshold pressure related API changes

---

examples/flow_polymer.cpp
examples/sim_poly2p_comp_reorder.cpp
examples/sim_poly2p_incomp_reorder.cpp
examples/sim_poly_fi2p_comp_ad.cpp

Use non-strict parse mode to avoid throwing.

use non-strict ParseMode.
